/* embed NAME FILE... > out.h
 * Writes the files as C byte arrays plus a table, so fbm-gpu carries its
 * OpenCL source without depending on the working directory. Plain C so that
 * any platform that can build fbm-gpu can also build this. */
#include <stdio.h>

int main(int argc, char **argv)
{
    if (argc < 3) {
        fprintf(stderr, "usage: embed NAME FILE...\n");
        return 2;
    }
    printf("/* Generated by tools/embed.c. Do not edit. */\n");
    for (int i = 2; i < argc; i++) {
        FILE *f = fopen(argv[i], "rb");
        int c, n = 0;
        if (!f) {
            perror(argv[i]);
            return 1;
        }
        printf("static const char %s_%d[] = {", argv[1], i - 2);
        while ((c = fgetc(f)) != EOF)
            printf("%s%d,", n++ % 24 ? "" : "\n", c);
        printf("0};\n");
        fclose(f);
    }
    printf("static const char *const %s[] = {", argv[1]);
    for (int i = 2; i < argc; i++)
        printf("%s_%d, ", argv[1], i - 2);
    printf("};\nstatic const char *const %s_names[] = {", argv[1]);
    for (int i = 2; i < argc; i++)
        printf("\"%s\", ", argv[i]);
    printf("};\n#define %s_COUNT %d\n", argv[1], argc - 2);
    return 0;
}
